# **CSE330 Coding Exam Spring 2025** (Total Marks : 15)

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from itertools import combinations
from numpy.polynomial import Polynomial
np.set_printoptions(precision=6, formatter={'all': lambda x: f'{x:f}'})

## Question 01 **[4 + 1 = 5 Marks]**
The **central difference approximation** of the first derivative of a function is given by:

$$ f'(x) \approx \frac{f(x+h)-f(x-h)}{2h} $$

Using the same central difference method, we can approximate the second derivative of a function as:

$$ f''(x) \approx \frac{f'(x+h)-f'(x-h)}{2h} $$

Now, using $h=0.01$, approximates the **second derivative** of $f(x) = x\cdot e^x$ at $x=2$ by following those steps:

a) Compute the required first derivatives using the central difference method, which are needed to find the second derivative at $x=2$. Print the results.

b) Apply the formula for the second derivative at $x=2$ by using the results of *part a*. Print the results.

In [2]:
#a
def central_diff(f,h,x):
  return (f(x+h)-f(x-h))/(2*h)

f = lambda x: x*(np.e**x)
h = 0.01
x = 2

f_x_1 = central_diff(f,h,x+h)
f_x_2 = central_diff(f,h,x-h)

print(f"f'(x+h) = {f_x_1}\nf'(x-h) = {f_x_2}")

f'(x+h) = 22.46520840678885
f'(x-h) = 21.874054362124884


In [3]:
#b
f_2 = (f_x_1 - f_x_2)/(2*h)
print(f"f''(x) = {f_2}")

f''(x) = 29.557702233198313


## Question 02 **[3 + 1 + 1 = 5 Marks]**


The general form of $n$ degree Lagrange polynomial is given by

$$p_n(x) = \sum_{k=0}^n f(x_k)̧\cdot l_k(x) = \sum_{k=0}^n y_k\cdot l_k(x)$$

where

$$l_k(x) = \prod_{j=0, j\neq k}^n \frac{x-x_j}{x_k-x_j}$$

Here, you are given $3$ data points:

\begin{array}{|c|c|c|}
\hline
i & x_i & y_i = f(x_i) \\
\hline
0 & 1 & 3 \\
1 & 2 & 4 \\
2 & 4 & 6 \\
\hline
\end{array}

**Tasks:**

a) Using the `Polynomial` class from the NumPy library, find the polynomials $l_0(x), l_1(x)$ and $l_2(x)$ and print them.

b) Find the interpolated polynomial $p_n(x)$ using $l_0(x), l_1(x)$ and $l_2(x)$ and print it.

c) Evaluate the polynomial $p_n(x)$ at the point $x=3$ and print the result.

In [4]:
#a
def l(k, x):
    n = len(x)
    assert (k < len(x))

    x_k = x[k]
    x_copy = np.delete(x, k)

    denominator = np.prod(x_copy - x_k)

    coeff = []

    for i in range(n):
        coeff.append(sum([np.prod(x) for x in combinations(x_copy, i)]) * (-1)**(i) / denominator)

    coeff.reverse()

    return Polynomial(coeff)

x_data = [1,2,4]
l0 = l(0,x_data)
l1 = l(1,x_data)
l2 = l(2,x_data)

print("l0(x):",l0)
print("l1(x):",l1)
print("l2(x):",l2)

l0(x): 2.666667 - 2.0 x + 0.333333 x**2
l1(x): -2.0 + 2.5 x - 0.5 x**2
l2(x): 0.333333 - 0.5 x + 0.166667 x**2


In [5]:
#b
y_data = [3,4,6]
p = (y_data[0]*l0)+(y_data[1]*l1)+(y_data[2]*l2)
print("p(x):",p)

p(x): 2.0 + 1.0 x


In [6]:
#c
x = 3
res = p(x)
print("pn(x) at the point  x=3:",res)

pn(x) at the point  x=3: 5.0


3 poly 1 poly 1num 1 matrix 1 matrix 1 matrix


## Question 03 **[3 + 1 + 1 = 5 Marks]**

In polynomial interpolation using the **Vandermonde matrix method**, the system of equations for the polynomial can be written as:
$$Xa = y$$
Where
\begin{equation}
X = \begin{bmatrix}
x_0^0 & x_0^1 & x_0^2  & \cdots & x_0^n\\
x_1^0 & x_1^1 & x_1^2 & \cdots &  x_1^n\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
x_n^0 & x_{n}^1 & x_n^2 & \cdots & x_n^n\\
\end{bmatrix}
\end{equation}

and

\begin{equation}
a = \begin{bmatrix}
a_0\\
a_1\\
\vdots\\
a_n\\
\end{bmatrix} \text{,  } y = \begin{bmatrix}
y_0\\
y_1\\
\vdots\\
y_n\\
\end{bmatrix}
\end{equation}

Now suppose the Vandermonde matrix $X$ is modified to:

\begin{equation}
X_0 = \begin{bmatrix}
x_0^n & x_0^{n-1} & x_0^{n-2}  & \cdots & x_0^0\\
x_1^n & x_1^{n-1} & x_1^{n-2} & \cdots &  x_1^0\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
x_n^n & x_{n}^{n-1} & x_n^{n-2} & \cdots & x_n^0\\
\end{bmatrix}
\end{equation}

**Tasks:**

a) Given the data points $(2, 5), (-3, 6), (-5, 1), (6, 12)$, construct and the modified Vandermonde matrix $X_0$ using a NumPy array and print it.

b)  Considering the change in the Vandermonde matrix from $X$ to $X_0$, the coeficient vector $a$ must also be updated to match the reversed powers of $x$. **Construct and print** the updated vectors $a$ using the same format.

c) Using the previously constructed matrix $X_0$, find the value of the modified coefficient vector $a_0$ by solving the system $X_0 a_0 = y$, where $a_0$ is the modified coefficient vector. Print the resulting NumPy array.

In [7]:
#a

def modified_vander(data_x, data_y):
  nodes = len(data_x)
  X = np.zeros((nodes,nodes))
  for row in range(nodes): # Making X matrix x^0, x^1, x^2 ..
    for col in range(nodes):
      X[row][col] = data_x[row]**(nodes-col-1)

  return X

data_x = np.array([2,-3,-5,6])
data_y = np.array([5,6,1,12])

Xo = modified_vander(data_x,data_y)
print("Xo:\n",Xo)

Xo:
 [[8.000000 4.000000 2.000000 1.000000]
 [-27.000000 9.000000 -3.000000 1.000000]
 [-125.000000 25.000000 -5.000000 1.000000]
 [216.000000 36.000000 6.000000 1.000000]]


In [8]:
#b
a = ["a^n","a^n-1","a^n-2","...","a^0"]
print("a:",a)

a: ['a^n', 'a^n-1', 'a^n-2', '...', 'a^0']


In [9]:
#c
X_inv = np.linalg.inv(Xo)
ao = np.dot(X_inv,data_y)
print("ao:\n",ao)

ao:
 [0.054762 -0.057143 -0.640476 6.071429]
