Instructions: Make a copy of this notebook and rename into the format `ID.ipynb` (example: `12345678.ipynb`). Read all the comments and write appropriate code after any place that says `# YOUR CODE HERE`. When the daily evaluation tasks are revealed, append their solutions at the end of this notebook.

# Part 1: Solving a linear system using inverse matrix - 2 Marks

We have a linear system

\begin{align}
&a_{11} x_1 + a_{12} x_2 +  \cdots  + a_{1n} x_n = b_1\\
&a_{21} x_1 + a_{22} x_2 +  \cdots + a_{2n} x_n = b_2\\
&\cdots\\
&a_{n1} x_1 + a_{n2} x_2 +  \cdots + a_{nn} x_n = b_n\\
\end{align}

It is convenient to express this system in the
matrix form

\begin{align}
Ax = b
\end{align}

where $A$ is an $n \times n$ square matrix with elements $a_{ij}$, and $x$, $b$ are $n \times 1$ vectors.

We have to keep in mind that this system will have a unique solution iff $A$ is non-singular, given by $x = A^{-1}b.$

In [1]:
import numpy as np
np.set_printoptions(precision=6, formatter={'all': lambda x: f'{x:f}'})

In [2]:
def get_result_by_inverse_matrix(A, b):
    # A and b are numpy arrays
    x = np.zeros(b.shape)

    # First check if the A is non-singular matrix.
    # The determinant of a non-singular matrix will be non-zero.
    # Return None if there is no unique solution to the linear equation.

    # YOUR CODE HERE
    inverse = None
    if(np.linalg.det(A)==0):
        print("singular matrix")
        return None # Return None when the matrix is singular
    else:
        inverse = np.linalg.inv(A)

    x = np.dot(inverse, b)

    # HINT:
    # You may use functions such as linalg.det(), linalg.inv() from numpy.

    return x

In [3]:
# Test case for the get_result_by_inverse_matrix(A, b) function.

data_A = np.array([[1, 2, 1], [1, -2, 2], [2, 12, -2]])
data_b = np.array([0,4,4])

test = get_result_by_inverse_matrix(data_A, data_b)
result = [11, -2.5, -6]

print(test)
print(result)

data_A = np.array([[1, 2, 1], [1, -2, 2], [2, 0, 3]])
data_b = np.array([0,4,4])

test = get_result_by_inverse_matrix(data_A, data_b)
result = None

print(test)
print(result)

[11.000000 -2.500000 -6.000000]
[11, -2.5, -6]
singular matrix
None
None


# Part 2: Gaussian elimination - 2 Marks

Gaussian elimination uses elementary row operations to transform the system to upper triangular form $Ux = y$.

Elementary row operations include swapping rows and adding multiples of one rowto another.
They won’t change the solution $x$, but will change the matrix $A$ and the right-hand side $b$.

The upper triangular matrix, $𝑈$, is defined as

\begin{bmatrix}
u_{11} & u_{12} & \cdots & u_{1n}\\
0 & u_{22} & \cdots & u_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & \cdots & 0 & u_{nn}\\
\end{bmatrix}


**Algorithm of Gaussian elimination**

Let $A^{(1)}=A$ and $b^{(1)}=b$. Then for each k from 1 to $n-1$, compute a new matrix $A^{(k+1)}$ and right-hand side $b^{(k+1)}$ by the following procedure:


1.   Define the row multipliers

\begin{align}
m_{ij} = \frac{a_{ik}^{(k)}}{a_{kk}^{(k)}}, i=k+1,\cdot \cdot \cdot,n.
\end{align}
2.   Use these to remove the unknown $x_k$ from equations $k + 1$ to $n$, leaving

\begin{align}
a_{ij}^{(k+1)}=a_{ij}^{(k)}-m_{ik}a_{kj}^{(k)}, b_{i}^{(k+1)}=b_{i}^{(k)}-m_{ik}b_{k}^{(k)}, i,j=k+1,\cdot \cdot \cdot, n.
\end{align}

It is helpful to combine these matrices to form an Augmented matrix (matrix $b$ is the fourth column). We will perform this row operations on the Augmented matrix. It takes care of both $A$ and $b$ matrixes at the same time.

After generating the upper triangular matrix, we have to apply **backward substitution method**.
For any $n \times n$ upper triangular system, $Ux = b$, the solution is:

\begin{align}
x_j = \frac{b_j-\sum_{k=j+1}^{n}u_{jk}x_k}{u_{jj}}, j = n, n-1, \cdot\cdot\cdot, 1.
\end{align}

Here we assumed that $det𝑈≠0$.


In [4]:
import sys

def get_result_gaussian_elimination(n, A):
    # n is the number of unknowns.
    # A is a numpy array representing the Augmented n x (n+1) matrix.
  x = np.zeros(n)

    # First check if the A is non-singular matrix.
    # The determinant of a non-singular matrix will be non-zero.
    # Return None if there is no unique solution to the linear equation.

    # YOUR CODE HERE

    # HINT:
    # Apply Gauss Elimination followed by Back Substitution
  a = A.copy()

  for i in range(n):
      if a[i][i] == 0.0:

          for k in range(i + 1, n):
              if a[k][i] != 0.0:
                  a[[i, k]] = a[[k, i]]
                  break

          else:

              return None


      for j in range(i+1, n):
          ratio = a[j][i]/a[i][i]
          for k in range(n+1):
              a[j][k] = a[j][k] - ratio * a[i][k]



  x[n-1] = a[n-1][n]/a[n-1][n-1]
  for i in range(n-2,-1,-1):
      x[i] = a[i][n]
      for j in range(i+1,n):
          x[i] = x[i] - a[i][j]*x[j]
      x[i] = x[i]/a[i][i]

  return x

In [5]:
# Test case for the get_result_gaussian_elimination(n, A) function.

data_n = 3
data_A = np.array([[1, 2, 1, 0], [1, -2, 2, 4], [2, 12, -2, 4]])

test = get_result_gaussian_elimination(data_n, data_A)
result = [11, -2.5, -6]

print(test)
print(result)

data_n = 3
data_A = np.array([[1, 2, 1, 0], [1, -2, 2, 4], [2, 0, 3, 4]])

test = get_result_gaussian_elimination(data_n, data_A)
result = None

print(test)
print(result)

[11.000000 -2.500000 -6.000000]
[11, -2.5, -6]
None
None


# Daily Evaluation - 4 Marks

In [6]:
import sys

def get_result_gaussian_elimination(n, A):
    # n is the number of unknowns.
    # A is a numpy array representing the Augmented n x (n+1) matrix.
  x = np.zeros(n)

    # First check if the A is non-singular matrix.
    # The determinant of a non-singular matrix will be non-zero.
    # Return None if there is no unique solution to the linear equation.

    # YOUR CODE HERE

    # HINT:
    # Apply Gauss Elimination followed by Back Substitution
  a = A.copy()
  b = np.zeros(A.shape)
  for i in range(n):
      if a[i][i] == 0.0:

          for k in range(i + 1, n):
              if a[k][i] != 0.0:
                  a[[i, k]] = a[[k, i]]
                  break

          else:
              return None


      for j in range(i+1, n):
          ratio = a[j][i]/a[i][i]
          for k in range(n+1):
              a[j][k] = a[j][k] - ratio * a[i][k]
              b[j][k] = ratio

  print(f"Row Multipliers:\n{b}")
  print(f"Upper Triangular Matrix:\n{a}")
  x[n-1] = a[n-1][n]/a[n-1][n-1]
  for i in range(n-2,-1,-1):
      x[i] = a[i][n]
      for j in range(i+1,n):
          x[i] = x[i] - a[i][j]*x[j]
      x[i] = x[i]/a[i][i]

  return x

In [7]:
data_n = 5
data_A = np.array([[1,2,3,4,5,30], [-1,2,3,4,5,18], [-1,4,3,4,5,24], [-1,4,-3,4,5,12], [-1,3,0,-2,0,6]])
print(f"Augmented Matris:\n{data_A}")
val = get_result_gaussian_elimination(data_n, data_A)
print(f"Solutions:\n{val}")

Augmented Matris:
[[1.000000 2.000000 3.000000 4.000000 5.000000 30.000000]
 [-1.000000 2.000000 3.000000 4.000000 5.000000 18.000000]
 [-1.000000 4.000000 3.000000 4.000000 5.000000 24.000000]
 [-1.000000 4.000000 -3.000000 4.000000 5.000000 12.000000]
 [-1.000000 3.000000 0.000000 -2.000000 0.000000 6.000000]]
Row Multipliers:
[[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
 [-1.000000 -1.000000 -1.000000 -1.000000 -1.000000 -1.000000]
 [1.500000 1.500000 1.500000 1.500000 1.500000 1.500000]
 [3.000000 3.000000 3.000000 3.000000 3.000000 3.000000]
 [-0.250000 -0.250000 -0.250000 -0.250000 -0.250000 -0.250000]]
Upper Triangular Matrix:
[[1.000000 2.000000 3.000000 4.000000 5.000000 30.000000]
 [0.000000 4.000000 6.000000 8.000000 10.000000 48.000000]
 [0.000000 0.000000 -3.000000 -4.000000 -5.000000 -18.000000]
 [0.000000 0.000000 0.000000 8.000000 10.000000 24.000000]
 [0.000000 0.000000 0.000000 0.000000 2.000000 6.000000]]
Solutions:
[6.000000 3.000000 2.000000 -0.750000 3